name: angulardart_boot
version: 0.1.0
description: Bootstrap repository for AngularDart applications

dependencies:
  angular: ^5.0.0-alpha+12
  angular_components: ^0.9.0-alpha+12
  angular_forms: ^2.0.0-alpha+4
  angular_router: ^2.0.0-alpha+11
  shelf: ^0.7.3+1
  shelf_static: ^0.2.7+1

dev_dependencies:
  build_runner: ^0.8.9
  build_web_compilers: ^0.4.0+1
