name: angulardart_boot
version: 0.1.0
description: Bootstrap repository for AngularDart applications

dependencies:
  angular: ^5.0.0-alpha+12
  angular_components: ^0.9.0-alpha+12
  angular_forms: ^2.0.0-alpha+4
  angular_router: ^2.0.0-alpha+11
