name: fullstack_dart
version: 0.1.0
description: Full-stack repository for AngularDart + Shelf applications

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+12
  angular_components: ^0.9.0-alpha+12
  angular_router: ^2.0.0-alpha+11
  angular_forms: ^2.0.0-alpha+4
  built_value: ^5.4.5
  shelf: ^0.7.3+1
  shelf_static: ^0.2.7+1

dev_dependencies:
  build_runner: ^0.8.9
  build_web_compilers: ^0.4.0+1
  built_value_generator: ^5.4.5
  webdev: ^0.2.1
